import { Button, VerticalBox, ListView, HorizontalBox, LineEdit } from "std-widgets.slint";
import {taskAddition} from "./taskAddition.slint";
import {subTask} from "./subTask.slint";
import {taskVisualiser} from "./TaskVisualiser.slint";
export component AppWindow inherits Window {
    min-width: 1000px;
    min-height: 500px;
    in-out property <string> myTask: "here";
    in-out property <int> counter: 0;
    //    in-out property <[{text: string}]> collected-tasks:[{ text: "working on rust" }, { text: "doing some home work" }];
in-out property <[string]> collected-tasks:["working on rust", "doing some home work"];
    in property <string> current-timer-state;
    in-out property <string> my-time: "00:00:00";
    callback request-increase-value();
    callback current-task(string);
    callback remove-task(int);
    callback timer-state(string);
    GridLayout {
        spacing: 0.2rem;
        Row {
            // CODE FOR THE PONODORO
            Rectangle {
                background: whitesmoke;
                min-width: (root.width / 3) * 2;
                VerticalLayout {
                    // THIS IS THE CODE FOR THE BUTTONS OF THE CLOCK
                    HorizontalLayout {
                        vertical-stretch: 2;
                        alignment: stretch;
                        Rectangle {
                            background: whitesmoke;
                            horizontal-stretch: 1;
                            // STORES THE BUTTONS FOR RESET, PAUSE AND START
                        HorizontalBox {
                                min-width: 20px;
                                Rectangle {
                                    // button to start and stop the timer
                            pause := Button {
                                        width: parent.width;
                                        height: parent.height;
                                        checkable: true;
                                        text: self.checked ? "ON" : "OFF";
                                        clicked => {
                                            self.checked ? timer-state("start") : timer-state("stop");
                                        }
                                    }
                                }

                                Rectangle {
                                    Button {
                                        width: parent.width;
                                        height: parent.height;
                                        text: "RESET";
                                        clicked => {
                                            timer-state("stop");
                                            pause.checked = true;
                                            timer-state("start")// if (pause.checked == true) {
                                            //     timer-state("stop");
                                            //     timer-state("reset");
                                            // } else {
                                            //     pause.checked = true;
                                            //     timer-state("start")
                                            // }
                                        }
                                    }
                                }
                            }
                        }

                        // counter for the work, short break and long break
                        Rectangle {
                            horizontal-stretch: 2;
                            background: whitesmoke;
                            HorizontalBox {
                                short-rest := Rectangle {
                                    border-radius: 15px;
                                    background: white;
                                    Text {
                                        x: (parent.width - self.width) / 2;
                                        y: (parent.height - self.height) / 2;
                                        text: "short-rest";
                                    }

                                    short-rest-hover := TouchArea {
                                        clicked => {
                                            active = !active;
                                        }
                                    }

                                    property <bool> active: true;
                                    states [
                                        active when !short-rest-hover.has-hover: {
                                            background: white;
                                        }
                                        active-hover when active && short-rest-hover.has-hover: {
                                            background: blue;
                                        }
                                    ]
                                }

                                working := Rectangle {
                                    border-radius: 15px;
                                    background: white;
                                    Text {
                                        x: (parent.width - self.width) / 2;
                                        y: (parent.height - self.height) / 2;
                                        text: "working";
                                    }

                                    working-hover := TouchArea {
                                        clicked => {
                                            active = !active;
                                        }
                                    }

                                    property <bool> active: true;
                                    states [
                                        active when !working-hover.has-hover: {
                                            background: white;
                                        }
                                        active-hover when active && working-hover.has-hover: {
                                            background: blue;
                                        }
                                    ]
                                }

                                long-rest := Rectangle {
                                    border-radius: 15px;
                                    background: white;
                                    Text {
                                        x: (parent.width - self.width) / 2;
                                        y: (parent.height - self.height) / 2;
                                        text: "long-rest";
                                    }

                                    long-rest-hover := TouchArea {
                                        clicked => {
                                            active = !active;
                                        }
                                    }

                                    property <bool> active: true;
                                    states [
                                        active when !long-rest-hover.has-hover: {
                                            background: white;
                                        }
                                        active-hover when active && long-rest-hover.has-hover: {
                                            background: blue;
                                        }
                                    ]
                                }
                            }
                        }
                    }

                    // THIS IS THE CODE FOR THE CLOCK
                    HorizontalLayout {
                        alignment: stretch;
                        vertical-stretch: 9;
                        Rectangle {
                            Text {
                                x: (parent.width - self.width) / 2;
                                y: (parent.height - self.height) / 2;
                                width: 90%;
                                font-size: 12rem;
                                text: my-time;
                            }
                        }
                    }

                    // THIS IS THE CODE FOR BOTTOM OF THE SCREEN
                    HorizontalLayout {
                        alignment: stretch;
                        vertical-stretch: 1;
                        Rectangle {
                            background: blue;
                        }
                    }
                }
            }

            // CODE FOR THE TASK MANU

            Rectangle {
                background: blue;
                min-width: (root.width / 3);
                VerticalBox {
                    VerticalBox {
                        taskAddition {
                            addedTask(task_name) => {
                                // Update myTask property with the new task name
                        current-task(task_name);
                            }
                        }
                    }

                    VerticalBox {
                        Text {
                            text: "Tasks";
                            font-size: 2rem;
                        }

                        ListView {
                            for task[idx] in collected-tasks: Rectangle {
                                HorizontalLayout {
                                    padding-bottom: 1rem;
                                    HorizontalBox {
                                        LineEdit {
                                            text: task;
                                        }

                                        Button {
                                            text: "remove";
                                            clicked => {
                                                remove-task(idx);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
