import { HorizontalBox } from "std-widgets.slint";
export component numberOfSession inherits HorizontalBox {
    min-width: 250px;
    spacing: 5px;
    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "Sessions";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "1";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "2";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: greenyellow;
        border-color: lightblue;
        Text {
            text: "3";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        Text {
            text: "4";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        Text {
            text: "5";
        }
    }
}
