import { HorizontalBox } from "std-widgets.slint";
export component sessionLength inherits HorizontalBox {
    min-width: 250px;
    spacing: 5px;
    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "Length";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "15min";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "25min";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "35min";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: greenyellow;
        border-color: lightblue;
        Text {
            text: "45min";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        Text {
            text: "55min";
        }
    }
}
