import { HorizontalBox } from "std-widgets.slint";
export component sessionLength inherits HorizontalBox {
    min-width: 250px;
    spacing: 5px;
    in-out property <int> selected-length-time:15;
    callback selectLength(int);
    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "Length";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "15min";
        }

        fifteen := TouchArea {
            clicked => {
                selected-length-time = 15;
                root.selectLength(selected-length-time);
            }
        }

        states [
            active-hover when fifteen.has-hover: {
                background: orange;
            }
            active when selected-length-time == 15: {
                background: yellow;
            }
        ]
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "25min";
        }

        twenty-five := TouchArea {
            clicked => {
                selected-length-time = 25;
                root.selectLength(selected-length-time);
            }
        }

        states [
            active-hover when twenty-five.has-hover: {
                background: orange;
            }
            active when selected-length-time == 25: {
                background: yellow;
                border-radius: 90px;
            }
        ]
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "35min";
        }

        thirty-five := TouchArea {
            clicked => {
                selected-length-time = 35;
                root.selectLength(selected-length-time);
            }
        }

        states [
            active-hover when thirty-five.has-hover: {
                background: orange;
            }
            active when selected-length-time == 35: {
                background: yellow;
                border-radius: 90px;
            }
        ]
    }

    Rectangle {
        border-radius: 15px;
        border-color: lightblue;
        Text {
            text: "45min";
        }

        fourty-five := TouchArea {
            clicked => {
                selected-length-time = 45;
                root.selectLength(selected-length-time);
            }
        }

        states [
            active-hover when fourty-five.has-hover: {
                background: orange;
            }
            active when selected-length-time == 45: {
                background: yellow;
                border-radius: 90px;
            }
        ]
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        Text {
            text: "55min";
        }

        fifty-five := TouchArea {
            clicked => {
                selected-length-time = 55;
                root.selectLength(selected-length-time);
            }
        }

        states [
            active-hover when fifty-five.has-hover: {
                background: orange;
            }
            active when selected-length-time == 55: {
                background: yellow;
                border-radius: 90px;
            }
        ]
    }
}
