import { HorizontalBox } from "std-widgets.slint";
export component sessionLength inherits HorizontalBox {
    min-width: 250px;
    spacing: 5px;
    callback selectLength(int);
    in-out property <[int]> collected-tasks:[15, 25, 35, 45, 55];
    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "Length";
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "15min";
        }

        TouchArea {
            clicked => {
                root.selectLength(15);
            }
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "25min";
        }

        TouchArea {
            clicked => {
                root.selectLength(25);
            }
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        border-color: lightblue;
        Text {
            text: "35min";
        }

        TouchArea {
            clicked => {
                root.selectLength(35);
            }
        }
    }

    Rectangle {
        border-radius: 15px;
        background: greenyellow;
        border-color: lightblue;
        Text {
            text: "45min";
        }

        TouchArea {
            clicked => {
                root.selectLength(45);
            }
        }
    }

    Rectangle {
        border-radius: 15px;
        background: whitesmoke;
        Text {
            text: "55min";
        }

        TouchArea {
            clicked => {
                root.selectLength(55);
            }
        }
    }
}
