import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";
import {subTask} from "./subTask.slint";

export component taskAddition inherits Rectangle {
    min-width: 500px;
    // Define addedTask callback property
    callback addedTask(string);
    VerticalBox {
        HorizontalBox {
            height: 25%;
            myTask := LineEdit {
                placeholder-text: "Add a Task Heading";
            }

            Button {
                text: "ADD";
                clicked => {
                    root.addedTask(myTask.text);
                }
            }
        }
    }
}
