import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";
import {subTask} from "./subTask.slint";

export component taskAddition inherits Rectangle {
    height: 15%;
    // Define addedTask callback property
    callback addedTask(string);
    HorizontalBox {
        myTask := LineEdit {
            placeholder-text: "Add a Task Heading";
        }

        Button {
            text: "ADD";
            clicked => {
                root.addedTask(myTask.text);
                myTask.text = ""
            }
        }
    }
}
