import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";

export component taskAddition inherits Rectangle {
    min-height: 300px;
    min-width: 500px;
    // Define addedTask callback property
    callback addedTask(string);
    VerticalBox {
        HorizontalBox {
            height: 10%;
            myTask := LineEdit {
                placeholder-text: "Add a Task Heading";
            }

            Button {
                text: "ADD";
                clicked => {
                    root.addedTask(myTask.text);
                }
            }
        }
    }
}
